# ...\config\config.yml
development:
  email:
    server: smtp.gmail.com
    port: 587
    domain: saitc-mty.com
    authentication: none
    username:
    password:
    contact_recipient: miguelcerverac@gmail.com
production:
  email:
    server: smtp.gmail.com
    port: 587
    domain: gmail.com
    authentication: login
    username: miguelcerverac@gmail.com
    password: mikeki.27
    contact_recipient: miguelcerverac@gmail.com
